apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harshith
  template:
    metadata:
      labels:
        app: harshith
    spec:
      containers:
        - name: travel-cont 
          image: harshithreddy628/travel-booking-system:v1.0
          ports:
            - containerPort: 4000

--- 

apiVersion: v1
kind: Service
metadata:
  name: travel-svc 
spec:
  type: LoadBalancer
  selector:
    app: harshith
  ports:
    - port: 4001
      targetPort: 4000
      