version: '3.6'

services:
  travel-app:
    build: .
    container_name: travel-system
    ports:
      - "4555:4000"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/travelEas
    depends_on:
      - mongodbs

  mongodbs:
    image: mongo:latest
    ports:
      - 27000:27017
    volumes:
      - travel-data:/data/db 

volumes:
  travel-data:
